- name: Commit and push if last_link.txt changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if [ -f last_link.txt ]; then
            git add last_link.txt
            git commit -m "Update last sent link" || echo "No changes to commit"
            git push
          else
            echo "last_link.txt topilmadi, xabar yuborish kutilmoqda."
          fi
